# Generated by Django 2.1.7 on 2019-04-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submissioncache_judged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsubmission',
            name='execution_time',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
