# Generated by Django 2.1.7 on 2019-04-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20190401_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsubmission',
            name='execution_time',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
    ]
