# Generated by Django 2.1.7 on 2019-04-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_auto_20190401_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsubmission',
            name='verdict',
            field=models.CharField(blank=True, default='...', max_length=500),
        ),
    ]
