# Generated by Django 2.1.7 on 2019-04-04 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_auto_20190404_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsubmission',
            name='problem_submitted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_m_submission', to='problems.Problem'),
        ),
        migrations.AlterField(
            model_name='mainsubmission',
            name='user_handle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_m_submission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissioncache',
            name='problem_submitted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_c_submission', to='problems.Problem'),
        ),
        migrations.AlterField(
            model_name='submissioncache',
            name='user_handle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_c_submission', to=settings.AUTH_USER_MODEL),
        ),
    ]
