# Generated by Django 2.1.7 on 2019-04-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsubmission',
            name='language',
            field=models.CharField(blank=True, choices=[('c_cpp', 'C++')], default='c_cpp', max_length=100),
        ),
        migrations.AlterField(
            model_name='submissioncache',
            name='language',
            field=models.CharField(blank=True, choices=[('c_cpp', 'C++')], default='c_cpp', max_length=100),
        ),
    ]
